# Usamos una imagen base de Python
FROM python:3.9

# Creamos un directorio de trabajo en el contenedor
WORKDIR /app

# Copiamos el archivo requirements.txt
COPY requirements.txt .

# Instalamos dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto del código
COPY . .

# Exponemos el puerto 5000 dentro del contenedor
EXPOSE 5000

# Comando para arrancar la app
CMD ["python", "app.py"]
